#!/usr/bin/env python3
"""
Skill Generator — produces a Course Buddy skill.md from the instance template + NLM data.
Constraint: C1 (stdlib + PyYAML only; no API calls)
Output: instances/[CourseCode]-[ShortName]/skill.md — drop into agents/course-buddyes/instances/
"""
from __future__ import annotations

import textwrap
from datetime import date
from pathlib import Path


class SkillGenerator:
    """
    Generates a Course Buddy skill file following the Socratic template in
    agents/course-buddyes/_course-buddy-instance-template.md.

    The generated skill:
    - Is named and tagged for the specific course.
    - Has a pre-populated concept dependency map (from NLM mind map, or from unit order).
    - Has a mastery tracker pre-filled with all unit concepts at level "Not started".
    - References the wiki index for supplemental context during coaching sessions.
    - Follows the Socratic flow defined in agents/course-buddy-template.md.
    """

    MASTERY_LEVELS = [
        "1 — Not started",
        "2 — Basic recall",
        "3 — Conceptual understanding",
        "4 — Application",
        "5 — Analysis and integration",
        "6 — Exam-ready mastery",
    ]

    def __init__(
        self,
        course_meta: dict,
        units: list[dict],
        nlm_data: dict,
        output_path: Path,
        dry_run: bool = False,
    ) -> None:
        self.meta = course_meta
        self.units = units
        self.nlm = nlm_data
        self.output_path = output_path
        self.dry_run = dry_run
        self.course_code: str = course_meta["course_code"]
        self.short_name: str = course_meta.get("short_name", self.course_code)
        self.course_name: str = course_meta.get("course_name", self.course_code)
        self.stream: str = course_meta.get("stream", "")
        self.semester: int = course_meta.get("semester", 0)
        self.instructor: str = course_meta.get("instructor", "")

    def generate(self) -> None:
        content = self._build()
        if self.dry_run:
            print(f"[DRY RUN] Would write: {self.output_path}")
        else:
            self.output_path.parent.mkdir(parents=True, exist_ok=True)
            self.output_path.write_text(content, encoding="utf-8")
            print(f"[OK] Skill: {self.output_path}")

    def _build(self) -> str:
        today = date.today().isoformat()
        code = self.course_code
        short = self.short_name
        name = self.course_name

        dep_map = self._build_dep_map()
        mastery_tracker = self._build_mastery_tracker()
        unit_summary = self._build_unit_summary()
        textbook_lines = self._build_textbook_lines()

        return textwrap.dedent(f"""\
            # Course Buddy — {code} — {short}

            *Generated by Course Buddy Builder on {today}. Do not edit the metadata block manually;
            run `build.py --refresh` to update AI-derived sections.*

            ---

            ## Course metadata

            | Field | Value |
            |-------|-------|
            | Course code | {code} |
            | Course name | {name} |
            | Short name | {short} |
            | Stream | {self.stream} |
            | Semester | {self.semester} |
            | Instructor | {self.instructor} |

            **Supplemental context**: Load `knowledge/{code}-{short}/wiki/index.md` at the start
            of every session with this student for this course.

            ---

            ## Textbooks and references

            {textbook_lines}

            ---

            ## Syllabus outcomes

            {unit_summary}

            ---

            ## Concept dependency map

            {dep_map}

            ---

            ## Assessment blueprint

            | Component | Weight | Coverage |
            |-----------|--------|----------|
            {self._build_assessment_table()}

            ---

            ## Mastery tracker

            *Update after each session. Target: all concepts at level 6 by exam day.*

            | Concept | Current level | Last evidence | Next practice |
            |---------|--------------|---------------|---------------|
            {mastery_tracker}

            ---

            ## Socratic session protocol

            Apply this sequence for every concept discussion:

            1. **Probe first** — "Before I explain, what do you already know about {{concept}}?"
            2. **Diagnose** — identify whether the gap is factual, conceptual, or application.
            3. **Explain** — adapt level to the student's current mastery (levels 1-6).
               - Level 1-2: analogy and plain language; no formula yet.
               - Level 3-4: formal definition, worked example, formula introduction.
               - Level 5-6: edge cases, complexity trade-offs, exam-pattern questions.
            4. **Sequence**: What → Why → How → What If
            5. **Close** — "Explain this back to me in one sentence." Then: one practice problem.
            6. **Update mastery tracker** after each session.

            **Wiki reference during session**: If the student is stuck, reference the corresponding
            concept page in `knowledge/{code}-{short}/wiki/[concept-slug].md` — point them to
            the Beginner or Intermediate section as appropriate.

            ---

            ## Integrity guardrail (AI use)

            Apply the REVA sequence: **Attempt → Assist → Augment → Automate**

            - Student must attempt the problem before receiving a hint.
            - AI assists with hints, questions, and structure — not direct answers.
            - AI augments quality after student understanding is visible.
            - AI automates only repetitive calculation once the concept is mastered.

            Mandatory explain-back prompt after any AI-assisted concept session:
            "What did you understand today about {{concept}} — not just what answer did you get?"

            ---

            ## Socratic session close

            End every session with:
            1. **Student summary** — student explains the session concept in their own words.
            2. **One practice problem** — student commits to solving it before next session.
            3. **One checkpoint date** — when will they review the mastery tracker entry?

            ---

            ## Evidence and portfolio

            After reaching mastery level 4+ on a concept, prompt:
            "This understanding can become Srujana Stage 2 evidence.
            Have you completed the corresponding workbook exercise? Have you solved a problem
            on LeetCode / Codeforces / similar? Is it documented in your portfolio?"

            Point to `knowledge/{code}-{short}/workbook.ipynb` for the structured exercise.
        """)

    def _build_dep_map(self) -> str:
        """Build a numbered dependency list from NLM concept deps or from unit order."""
        nlm_deps: list[str] = self.nlm.get("concept_deps", [])
        if nlm_deps:
            lines = "\n".join(f"{i+1}. {dep}" for i, dep in enumerate(nlm_deps[:20]))
            return f"*Source: NotebookLM mind map*\n\n{lines}"

        # Fallback: unit-order dependency list
        lines_list = []
        i = 1
        for unit in self.units:
            for concept in unit.get("concepts", []):
                lines_list.append(f"{i}. {concept} ({unit['title'].split('—')[0].strip()})")
                i += 1
        return "*Source: course descriptor unit order (NotebookLM mind map not available)*\n\n" + "\n".join(lines_list)

    def _build_mastery_tracker(self) -> str:
        rows = []
        for unit in self.units:
            for concept in unit.get("concepts", []):
                rows.append(f"| {concept} | 1 — Not started | | |")
        return "\n".join(rows) if rows else "| (No concepts parsed) | | | |"

    def _build_unit_summary(self) -> str:
        lines = []
        for i, unit in enumerate(self.units, 1):
            title = unit.get("title", f"Unit {i}")
            outcomes = unit.get("outcomes", [])
            out_str = "; ".join(outcomes) if outcomes else "_Not specified_"
            lines.append(f"{i}. **{title}** — {out_str}")
        return "\n".join(lines) if lines else "_No units parsed from course descriptor_"

    def _build_assessment_table(self) -> str:
        # Generic fallback — course descriptor assessment blueprint is in the body text
        return (
            "| _See course descriptor for full breakdown_ | | |"
        )

    def _build_textbook_lines(self) -> str:
        textbooks = self.meta.get("textbooks") or []
        references = self.meta.get("references") or []
        lines = []
        for t in textbooks:
            title = t.get("title", "")
            authors = t.get("authors", "")
            edition = t.get("edition", "")
            free_url = t.get("free_url", "")
            link = f" ([free]({free_url}))" if free_url else ""
            lines.append(f"- *{title}* — {authors} ({edition} ed.){link}")
        for ref in references:
            lines.append(f"- {ref}")
        return "\n".join(lines) if lines else "_No textbooks or references listed_"
