#!/usr/bin/env python3
"""
Wiki Generator — produces Obsidian-format Markdown knowledge wiki from NLM data + course descriptor.
Constraint: C1 (stdlib + PyYAML only; no API calls)
Output: wiki/ folder with index.md, per-concept pages (3 levels), glossary.md,
        concept-map.md (Mermaid), and .obsidian/app.json vault stub.
"""
from __future__ import annotations

import json
import re
import textwrap
from datetime import date
from pathlib import Path
from typing import Any


def _slug(text: str) -> str:
    """Convert a concept name to a filesystem-safe slug."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def _yaml_header(tags: list[str], extra: dict | None = None) -> str:
    tag_str = "\n".join(f"  - {t}" for t in tags)
    extra_str = ""
    if extra:
        for k, v in extra.items():
            extra_str += f"{k}: {v!r}\n"
    return f"---\ntags:\n{tag_str}\n{extra_str}---\n\n"


class WikiGenerator:
    """
    Generates all wiki pages for a course.
    Writes to output_dir/.
    """

    def __init__(
        self,
        course_meta: dict,
        units: list[dict],
        evidence_map: list[dict],
        nlm_data: dict,
        output_dir: Path,
        dry_run: bool = False,
    ) -> None:
        self.meta = course_meta
        self.units = units
        self.evidence_map = evidence_map
        self.nlm = nlm_data
        self.out = output_dir
        self.dry_run = dry_run
        self.course_code: str = course_meta["course_code"]
        self.short_name: str = course_meta.get("short_name", self.course_code)
        self.course_name: str = course_meta.get("course_name", self.course_code)

    def generate(self) -> None:
        self._write_obsidian_stub()
        self._write_index()
        self._write_concept_pages()
        self._write_glossary()
        self._write_concept_map()
        print(f"[{'DRY RUN' if self.dry_run else 'OK'}] Wiki: {self.out}")

    # ── Writers ──────────────────────────────────────────────────────────────

    def _write(self, path: Path, content: str) -> None:
        if self.dry_run:
            print(f"[DRY RUN] Would write: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")

    def _write_obsidian_stub(self) -> None:
        """Minimal .obsidian/app.json so the wiki folder opens as an Obsidian vault."""
        config = {
            "promptDelete": False,
            "defaultViewMode": "preview",
            "alwaysUpdateLinks": True,
        }
        self._write(
            self.out / ".obsidian" / "app.json",
            json.dumps(config, indent=2),
        )

    def _write_index(self) -> None:
        code = self.course_code
        name = self.course_name
        semester = self.meta.get("semester", "")
        stream = self.meta.get("stream", "")
        instructor = self.meta.get("instructor", "")
        today = date.today().isoformat()

        # Unit links table
        unit_rows = "\n".join(
            f"| {u['title']} | {', '.join(f'[[{_slug(c)}]]' for c in u['concepts'][:3])}{'...' if len(u['concepts']) > 3 else ''} |"
            for u in self.units
        )

        # Audio embed line (if available)
        audio_embed = (
            "\n> 🎧 **Audio overview**: [[audio-overview.mp3]] *(generated by NotebookLM)*\n"
            if self.nlm.get("audio_path")
            else ""
        )

        content = textwrap.dedent(f"""\
            {_yaml_header(
                [code, stream, "index", "course-buddy"],
                {"course": f'"{code}"', "updated": f'"{today}"'}
            )}\
            # {code} — {name}

            | Field | Value |
            |-------|-------|
            | Stream | {stream} |
            | Semester | {semester} |
            | Instructor | {instructor} |
            | Generated | {today} |
            {audio_embed}
            ---

            ## Units
            | Unit | Key concepts (sample) |
            |------|-----------------------|
            {unit_rows}

            ---

            ## Quick navigation
            - [[glossary]] — All key terms
            - [[concept-map]] — Visual dependency graph
            - [[../workbook]] — Practice workbook (Jupyter)
            - [[../CONTRIBUTING]] — How to contribute

            ---

            ## About this wiki
            This knowledge wiki was generated by the [Course Buddy Builder](../../../tools/course-buddy-builder/README.md)
            using [Google NotebookLM](https://notebooklm.google.com) and the
            [REVA AI Tutor Philosophy](../../../references/ai-tutor-philosophy.md).

            Pages are available at three levels: **Beginner**, **Intermediate**, **Advanced**.
            Navigate using the `level:` tag in each page's frontmatter.
        """)
        self._write(self.out / "index.md", content)

    def _write_concept_pages(self) -> None:
        """One Markdown file per concept, three-level sections."""
        # Build a lookup from NLM study guide: section heading → content
        nlm_sections = self._parse_study_guide_sections()
        nlm_deps = self.nlm.get("concept_deps", [])

        all_concepts: list[tuple[str, str]] = []  # (unit_title, concept_name)
        for unit in self.units:
            for concept in unit.get("concepts", []):
                all_concepts.append((unit["title"], concept))

        for unit_title, concept in all_concepts:
            sl = _slug(concept)
            # Try to find matching NLM content for this concept
            nlm_content = self._find_nlm_content(concept, nlm_sections)

            # Find related concepts (others in same unit)
            unit_concepts = [
                c for u in self.units if u["title"] == unit_title for c in u["concepts"]
            ]
            related = [f"[[{_slug(c)}]]" for c in unit_concepts if c != concept]

            # Evidence mapping
            evidence = next(
                (
                    row["evidence"]
                    for row in self.evidence_map
                    if unit_title.split("—")[0].strip() in row.get("unit", "")
                ),
                "See Srujana Evidence Mapping table",
            )

            content = self._concept_page(concept, unit_title, nlm_content, related, evidence)
            self._write(self.out / f"{sl}.md", content)

    def _concept_page(
        self,
        concept: str,
        unit_title: str,
        nlm_content: dict[str, str],
        related: list[str],
        evidence: str,
    ) -> str:
        today = date.today().isoformat()
        code = self.course_code

        beginner = nlm_content.get(
            "beginner",
            f"*Beginner-level explanation for **{concept}** — to be completed.*\n\n"
            "Use an everyday analogy to introduce this concept without jargon.",
        )
        intermediate = nlm_content.get(
            "intermediate",
            f"*Intermediate-level explanation for **{concept}** — to be completed.*\n\n"
            "Provide the formal definition, a worked example, and the key formula or algorithm.",
        )
        advanced = nlm_content.get(
            "advanced",
            f"*Advanced-level discussion for **{concept}** — to be completed.*\n\n"
            "Explore edge cases, complexity nuances, and research connections.",
        )
        related_str = " · ".join(related) if related else "_None yet_"

        return textwrap.dedent(f"""\
            {_yaml_header(
                [code, _slug(concept), "concept"],
                {
                    "course": f'"{code}"',
                    "unit": f'"{unit_title}"',
                    "level": '"all"',
                    "updated": f'"{today}"',
                }
            )}\
            # {concept}

            **Unit**: {unit_title}
            **Related concepts**: {related_str}

            ---

            ## Beginner

            {beginner}

            ---

            ## Intermediate

            {intermediate}

            ---

            ## Advanced

            {advanced}

            ---

            ## Evidence link

            {evidence}

            > To turn this understanding into Srujana portfolio evidence:
            > open the [[../workbook]] and complete the exercise for this concept.

            ---

            ## Student contributions

            *No contributions yet. Add yours to `student-contributions/{_slug(concept)}-[reva-id].md`.*
        """)

    def _write_glossary(self) -> None:
        today = date.today().isoformat()
        code = self.course_code

        # Collect all concepts across all units
        all_concepts = [c for u in self.units for c in u.get("concepts", [])]
        rows = "\n".join(
            f"| [[{_slug(c)}\\|{c}]] | _Definition to be confirmed — see concept page._ |"
            for c in sorted(all_concepts)
        )

        content = textwrap.dedent(f"""\
            {_yaml_header([code, "glossary"], {"course": f'"{code}"', "updated": f'"{today}"'})}\
            # Glossary — {self.course_name}

            All key terms in this course, linked to their full concept pages.

            | Term | Short definition |
            |------|-----------------|
            {rows}

            ---

            *This glossary is auto-generated. Definitions are populated from NotebookLM study guide
            text. Corrections and improvements welcome via `student-contributions/`.*
        """)
        self._write(self.out / "glossary.md", content)

    def _write_concept_map(self) -> None:
        today = date.today().isoformat()
        code = self.course_code
        mind_map = self.nlm.get("mind_map_json", {})

        # Build a Mermaid graph from unit→concept dependencies
        mermaid_lines: list[str] = []
        for unit in self.units:
            unit_node = f'U_{_slug(unit["title"])[:20].replace("-", "_")}'
            mermaid_lines.append(f'    {unit_node}["{unit["title"][:40]}"]')
            for concept in unit.get("concepts", []):
                concept_node = f'C_{_slug(concept)[:20].replace("-", "_")}'
                mermaid_lines.append(f'    {concept_node}(("{concept[:30]}"))')
                mermaid_lines.append(f"    {unit_node} --> {concept_node}")

        mermaid_body = "\n".join(mermaid_lines) or "    A[No concepts parsed]"

        # Append NLM mind map JSON as a code block (for reference / future tooling)
        nlm_json_block = ""
        if mind_map:
            nlm_json_block = (
                "\n\n## Raw NotebookLM mind map (JSON)\n\n"
                "```json\n"
                + json.dumps(mind_map, indent=2, ensure_ascii=False)[:2000]
                + ("\n... (truncated)" if len(json.dumps(mind_map)) > 2000 else "")
                + "\n```"
            )

        content = textwrap.dedent(f"""\
            {_yaml_header([code, "concept-map"], {"course": f'"{code}"', "updated": f'"{today}"'})}\
            # Concept Map — {self.course_name}

            ```mermaid
            graph TD
            {mermaid_body}
            ```
            {nlm_json_block}
        """)
        self._write(self.out / "concept-map.md", content)

    # ── NLM content helpers ───────────────────────────────────────────────────

    def _parse_study_guide_sections(self) -> dict[str, str]:
        """
        Parse the NLM study guide Markdown into a dict keyed by section heading.
        Key: lowercased heading text. Value: section body.
        """
        text: str = self.nlm.get("study_guide_md", "")
        sections: dict[str, str] = {}
        current_key = ""
        current_lines: list[str] = []

        for line in text.splitlines():
            heading = re.match(r"^#{1,3} (.+)", line)
            if heading:
                if current_key:
                    sections[current_key] = "\n".join(current_lines).strip()
                current_key = heading.group(1).lower()
                current_lines = []
            else:
                current_lines.append(line)

        if current_key:
            sections[current_key] = "\n".join(current_lines).strip()

        return sections

    def _find_nlm_content(self, concept: str, sections: dict[str, str]) -> dict[str, str]:
        """
        Try to find NLM study guide content matching the concept name.
        Returns dict with optional 'beginner', 'intermediate', 'advanced' keys.
        """
        concept_lower = concept.lower()
        # Try exact section match first, then partial
        for key, body in sections.items():
            if concept_lower in key:
                # Heuristic: first half of body → beginner, second half → intermediate
                lines = body.splitlines()
                mid = max(1, len(lines) // 2)
                return {
                    "beginner": "\n".join(lines[:mid]).strip() or body,
                    "intermediate": "\n".join(lines[mid:]).strip() or body,
                }
        return {}
